version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finance-tracker-db
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fakha
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - finance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transactions"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: finance-tracker-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=postgres port=5432 user=postgres password=fakha dbname=transactions sslmode=disable"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      GIN_MODE: "release"
      PORT: "8080"
      EXCHANGE_API_ENDPOINT: "https://api.exchangerate-api.com/v4/latest/USD"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  finance-network:
    driver: bridge